# Generated by Django 2.1.10 on 2019-07-30 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_auto_20190419_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datosmedicos',
            name='av1_data',
        ),
        migrations.RemoveField(
            model_name='datosmedicos',
            name='av2_data',
        ),
        migrations.RemoveField(
            model_name='datosmedicos',
            name='av3_data',
        ),
        migrations.RemoveField(
            model_name='datosmedicos',
            name='av4_data',
        ),
        migrations.RemoveField(
            model_name='datosmedicos',
            name='av5_data',
        ),
        migrations.RemoveField(
            model_name='datosmedicos',
            name='av6_data',
        ),
        migrations.RemoveField(
            model_name='datosmedicos',
            name='avf_data',
        ),
        migrations.RemoveField(
            model_name='datosmedicos',
            name='avl_data',
        ),
        migrations.RemoveField(
            model_name='datosmedicos',
            name='avr_data',
        ),
        migrations.RemoveField(
            model_name='datosmedicos',
            name='d1_data',
        ),
        migrations.RemoveField(
            model_name='datosmedicos',
            name='d2_data',
        ),
        migrations.RemoveField(
            model_name='datosmedicos',
            name='d3_data',
        ),
        migrations.RemoveField(
            model_name='datosmedicos',
            name='general_data',
        ),
    ]
