# Generated by Django 2.1.10 on 2019-08-18 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_auto_20190730_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='RFDataModelFirst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QRSTA_v5', models.FloatField(blank=True, null=True)),
                ('QRSA_v5', models.FloatField(blank=True, null=True)),
                ('T_v5', models.FloatField(blank=True, null=True)),
                ('T_DI', models.FloatField(blank=True, null=True)),
                ('P', models.FloatField(blank=True, null=True)),
                ('S_v3', models.FloatField(blank=True, null=True)),
                ('Heart_rate', models.FloatField(blank=True, null=True)),
                ('QRS_duration', models.FloatField(blank=True, null=True)),
                ('Number_of_intrinsic_deflections_linear_v1', models.FloatField(blank=True, null=True)),
                ('R_wave_avr', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
