# Generated by Django 2.2.4 on 2019-08-30 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0004_rfdatamodelfirst'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=10, null=True)),
                ('calification', models.IntegerField(blank=True, null=True)),
                ('hit', models.BooleanField(blank=True, null=True)),
            ],
        ),
    ]
