# Generated by Django 2.1.10 on 2019-09-18 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0005_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='RFDataModelSecond',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Heart_rate', models.FloatField(blank=True, null=True)),
                ('R_prima_v2', models.FloatField(blank=True, null=True)),
                ('Q_v3', models.FloatField(blank=True, null=True)),
                ('QRS_duration', models.FloatField(blank=True, null=True)),
                ('Q_DII', models.FloatField(blank=True, null=True)),
                ('R_prima_R_v1', models.FloatField(blank=True, null=True)),
                ('Número_de_deflexiones_intrínsecas_en_v1', models.FloatField(blank=True, null=True)),
                ('T_v4', models.FloatField(blank=True, null=True)),
                ('T_v5', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
