# Generated by Django 2.1.10 on 2019-09-18 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0006_rfdatamodelsecond'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rfdatamodelsecond',
            old_name='Número_de_deflexiones_intrínsecas_en_v1',
            new_name='Numero_de_deflexiones_intrinsecas_en_v1',
        ),
    ]
